# Generated by Django 5.1.6 on 2025-02-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ad2000',
            field=models.CharField(blank=True, help_text='AD2000 identifier from LDAP', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='Not Active', max_length=20),
        ),
    ]
