# Generated by Django 5.1.6 on 2025-02-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_ad2000_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ldap_password',
            field=models.CharField(blank=True, help_text='LDAP password (store securely in production!)', max_length=255, null=True),
        ),
    ]
