# Generated by Django 5.1.6 on 2025-05-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_role_permissions_alter_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(default='no description', max_length=255),
        ),
    ]
