# Generated by Django 5.1.6 on 2026-01-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_role_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ldap_password',
        ),
    ]
