# Generated by Django 5.1.6 on 2026-01-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_ldap_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_view',
            field=models.CharField(choices=[('business', 'Business View'), ('department', 'Department View')], default='business', help_text='Default view for this user (set by admin)', max_length=20),
        ),
    ]
