# Generated by Django 5.1.6 on 2026-02-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_default_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='societe',
            field=models.CharField(blank=True, help_text='Company/Société from LDAP', max_length=255, null=True),
        ),
    ]
