# Generated by Django 5.1.6 on 2026-02-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_societe_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ad_groups',
            field=models.JSONField(blank=True, default=list, help_text='Cached list of AD groups'),
        ),
    ]
