# Generated by Django 5.1.6 on 2026-04-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_ad_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='societe',
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_consolide',
            field=models.BooleanField(default=False, help_text='Accès à la page des rapports consolidés'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='direction',
            field=models.CharField(blank=True, help_text='Direction from LDAP', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pole',
            field=models.CharField(blank=True, help_text='Pôle from LDAP', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='default_view',
            field=models.CharField(choices=[('direction', 'Direction View'), ('department', 'Department View')], default='direction', help_text='Default view for this user (set by admin)', max_length=20),
        ),
    ]
