# Generated by Django 5.1.6 on 2026-04-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_societe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_view',
            field=models.CharField(choices=[('direction', 'Direction View'), ('pole', 'Pôle View')], default='direction', help_text='Default view for this user (set by admin)', max_length=20),
        ),
    ]
