# Generated by Django 5.1.6 on 2026-04-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_default_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False, help_text='Indicates if the user has completed the onboarding guide'),
        ),
    ]
