# Generated by Django 5.1.6 on 2026-04-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_anomalie',
            field=models.BooleanField(default=False, help_text='Accès à la page des rapports anomalies'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_direction',
            field=models.BooleanField(default=True, help_text='Accès à la vue Direction'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_pole',
            field=models.BooleanField(default=False, help_text='Accès à la vue Pôle'),
        ),
    ]
