# Generated by Django 5.1.6 on 2026-09-29 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0025_alter_customfolder_view_type'),
        ('users', '0023_mobileapisession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapisession',
            name='app_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mobileapisession',
            name='device',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='mobileapisession',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='powerbi_report.reportref'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], default='web', max_length=10),
        ),
    ]
