services:
  db:
    image: postgres:16-alpine
    container_name: PBI_DB
    restart: unless-stopped
    environment:
      POSTGRES_DB: cbi_db
      POSTGRES_USER: cbi_user
      POSTGRES_PASSWORD: cbi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5222:5222"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cbi_user -d cbi_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    container_name: PBI
    build: .
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8222 --workers 4 config.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8222:8222"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
