# Generated by Django 5.1.6 on 2026-09-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('powerbi_report', '0026_mobile_logo_and_phone_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMobileLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('source_modified', models.CharField(blank=True, default='', max_length=64)),
                ('format_version', models.PositiveSmallIntegerField(default=1)),
                ('checked_at', models.DateTimeField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_layout', to='powerbi_report.reportref')),
            ],
        ),
    ]
