"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

def _config_bool(name: str, default: bool = False) -> bool:
    """Parse relaxed boolean env values while rejecting unknown values."""
    raw_value = config(name, default=str(default))
    if isinstance(raw_value, bool):
        return raw_value

    normalized = str(raw_value).strip().lower()
    truthy = {"1", "true", "yes", "on", "debug"}
    falsy = {"0", "false", "no", "off", "release", "prod", "production", ""}
    if normalized in truthy:
        return True
    if normalized in falsy:
        return False
    raise ValueError(f"Invalid truth value for {name}: {raw_value!r}")


def _config_list(name: str, default: str = "") -> list[str]:
    raw_value = config(name, default=default)
    return [item.strip() for item in raw_value.split(",") if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production.
DEBUG = _config_bool("DEBUG", default=False)

# ALLOWED_HOSTS = _config_list("ALLOWED_HOSTS", default="127.0.0.1,localhost")
ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = _config_list("CSRF_TRUSTED_ORIGINS", default="")

# Base URL of your report server 

POWERBI_REPORT_SERVER_URL = config("POWERBI_REPORT_SERVER_URL")

# All PBIRS server URLs (comma-separated). Defaults to the single URL above.
POWERBI_REPORT_SERVER_URLS = _config_list(
    "POWERBI_REPORT_SERVER_URLS",
    default=config("POWERBI_REPORT_SERVER_URL"),
)


# LDAP Configuration
LDAP_SERVER_NAME = config("LDAP_SERVER_NAME")
LDAP_DOMAIN = config("LDAP_DOMAIN")
LDAP_SEARCH_BASE = config("LDAP_SEARCH_BASE")
LDAP_PORT = config("LDAP_PORT", default=389, cast=int)
LDAP_USE_SSL = _config_bool("LDAP_USE_SSL", default=False)
LDAP_CONNECT_TIMEOUT = config("LDAP_CONNECT_TIMEOUT", default=8, cast=int)
LDAP_RECEIVE_TIMEOUT = config("LDAP_RECEIVE_TIMEOUT", default=20, cast=int)
LDAP_ENABLE_PORT_FALLBACK = _config_bool("LDAP_ENABLE_PORT_FALLBACK", default=True)
LDAP_SERVER_ALTERNATES = [
    host.strip()
    for host in config("LDAP_SERVER_ALTERNATES", default="").split(",")
    if host.strip()
]

# LDAP Service Account (for user sync operations)
LDAP_SERVICE_USERNAME = config("LDAP_SERVICE_USERNAME", default="")
LDAP_SERVICE_PASSWORD = config("LDAP_SERVICE_PASSWORD", default="")

# Report permission sync should normally be handled by manual/admin-triggered
# sync or an external hourly scheduler, not by every login.
PBIRS_SYNC_ON_LOGIN = _config_bool("PBIRS_SYNC_ON_LOGIN", default=False)
PBIRS_REFRESH_STATUS_LIVE = _config_bool("PBIRS_REFRESH_STATUS_LIVE", default=False)
PBIRS_REFRESH_STATUS_MAX_REPORTS = config("PBIRS_REFRESH_STATUS_MAX_REPORTS", default=40, cast=int)
PBIRS_REFRESH_STATUS_TIMEOUT = config("PBIRS_REFRESH_STATUS_TIMEOUT", default=2, cast=int)
PBIRS_REFRESH_STATUS_MAX_SECONDS = config("PBIRS_REFRESH_STATUS_MAX_SECONDS", default=20, cast=int)
PBIRS_SYNC_POLICY_TIMEOUT = config("PBIRS_SYNC_POLICY_TIMEOUT", default=15, cast=int)
PBIRS_SYNC_POLICY_RETRIES = config("PBIRS_SYNC_POLICY_RETRIES", default=2, cast=int)
PBIRS_SYNC_POLICY_RETRY_DELAY = config("PBIRS_SYNC_POLICY_RETRY_DELAY", default=1.5, cast=float)
PBIRS_SYNC_POLICY_REQUEST_DELAY = config("PBIRS_SYNC_POLICY_REQUEST_DELAY", default=0.05, cast=float)

# Role names (centralized to avoid hardcoded strings)
ADMIN_ROLE_NAME = "admin"
USER_ROLE_NAME = "user"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'tickets',

    'notifications',
    'powerbi_report',
    'guardian',
    'easyaudit',




]


LOGIN_URL = '/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'easyaudit.middleware.easyaudit.EasyAuditMiddleware',

]
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', 
    'guardian.backends.ObjectPermissionBackend',
)

SESSION_ENGINE = 'django.contrib.sessions.backends.db' 
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.user_permissions',
                
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DB_ENGINE = config('DB_ENGINE', default='postgresql').strip().lower()
if DB_ENGINE in {'sqlite', 'sqlite3'}:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': config('SQLITE_NAME', default=str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='cbi_db'),
            'USER': config('DB_USER', default='cbi_user'),
            'PASSWORD': config('DB_PASSWORD', default='cbi_password'),
            'HOST': config('DB_HOST', default='db'),
            'PORT': config('DB_PORT', default='5432'),
            'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=60, cast=int),
        }
    }

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'users.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = config('TIME_ZONE', default='Africa/Algiers')

USE_I18N = True

USE_TZ = True


# Security hardening for production deployments.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = _config_bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = _config_bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = config('SECURE_REFERRER_POLICY', default='strict-origin-when-cross-origin')
SECURE_SSL_REDIRECT = _config_bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000 if not DEBUG else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _config_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG)
SECURE_HSTS_PRELOAD = _config_bool('SECURE_HSTS_PRELOAD', default=not DEBUG)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'powerbi_report': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
