# Generated by Django 5.1.6 on 2026-02-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('bibliotheque', 'Bibliothèque'), ('cbi', 'CBI')], default='cbi', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('bug', 'Bug Report'), ('dashboard', 'Dashboard Request'), ('refresh', 'Refresh Request'), ('other', 'Other')], max_length=20),
        ),
    ]
