# Generated by Django 5.1.6 on 2026-02-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_attachment_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('bibliotheque', 'Bibliotheque'), ('cbi', 'CBI')], default='cbi', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('closed', 'Ferme'), ('rejected', 'Rejete')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('bug', 'Signalement de bug'), ('dashboard', 'Demande de dashboard'), ('refresh', "Demande d'actualisation"), ('other', 'Autre')], max_length=20),
        ),
    ]
