# Generated by Django 5.1.6 on 2026-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_category_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('bibliotheque', 'Bibliotheque'), ('cbi', 'CBI')], default='cbi', max_length=20),
        ),
    ]
