# Generated by Django 5.1.6 on 2026-04-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('bug', 'Signalement de bug'), ('dashboard', 'Demande de dashboard'), ('refresh', "Demande d'actualisation"), ('access', "Demande d'accès"), ('other', 'Autre')], max_length=20),
        ),
    ]
