# Generated by Django 5.1.6 on 2026-04-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_messages_attachments/'),
        ),
    ]
