# Generated by Django 5.1.6 on 2025-03-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0002_report_reportaccess'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportaccess',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reportaccess',
            name='has_access',
        ),
        migrations.RemoveField(
            model_name='reportaccess',
            name='report',
        ),
    ]
