# Generated by Django 5.1.6 on 2025-03-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0003_alter_reportaccess_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportaccess',
            name='reports',
            field=models.ManyToManyField(blank=True, to='powerbi_report.report'),
        ),
    ]
