# Generated by Django 5.1.6 on 2025-07-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0004_reportaccess_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerbireport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='powerbireport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='powerbireport',
            name='name',
        ),
        migrations.RemoveField(
            model_name='powerbireport',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='reportaccess',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='reportaccess',
            name='user',
        ),
    ]
