# Generated by Django 5.1.6 on 2025-07-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0005_remove_powerbireport_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
