# Generated by Django 5.1.6 on 2025-08-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0006_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
