# Generated by Django 5.1.6 on 2026-01-26 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0007_refresh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbirs_id', models.CharField(help_text='Report ID from PBIRS (UUID)', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(help_text='Path on PBIRS server (e.g., /Sales/Q1)', max_length=1024)),
                ('embed_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Reference',
                'verbose_name_plural': 'Report References',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('view_type', models.CharField(choices=[('business', 'Business Folders'), ('department', 'Department/Role')], help_text='Which custom view this folder belongs to', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within parent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='powerbi_report.customfolder')),
            ],
            options={
                'verbose_name': 'Custom Folder',
                'verbose_name_plural': 'Custom Folders',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FolderReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within folder')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_items', to='powerbi_report.customfolder')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_assignments', to='powerbi_report.reportref')),
            ],
            options={
                'verbose_name': 'Folder Report Item',
                'verbose_name_plural': 'Folder Report Items',
                'ordering': ['order', 'report__name'],
                'unique_together': {('folder', 'report')},
            },
        ),
    ]
