# Generated by Django 5.1.6 on 2026-01-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0008_custom_virtual_folders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='PowerBIReport',
        ),
        migrations.DeleteModel(
            name='Refresh',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportAccess',
        ),
    ]
