# Generated by Django 5.1.6 on 2026-02-09 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0010_reportref_modified_at_reportref_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('users_synced', models.PositiveIntegerField(default=0)),
                ('permissions_created', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Sync Log',
                'verbose_name_plural': 'Permission Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='powerbi_report.reportref')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Report Permission',
                'verbose_name_plural': 'User Report Permissions',
                'indexes': [models.Index(fields=['user'], name='powerbi_rep_user_id_4d908d_idx'), models.Index(fields=['report'], name='powerbi_rep_report__7fec4b_idx')],
                'unique_together': {('user', 'report')},
            },
        ),
    ]
