# Generated by Django 5.1.6 on 2026-02-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0011_user_report_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreportpermission',
            name='is_direct',
            field=models.BooleanField(default=True, help_text='True if permission is assigned directly to user, False if via Group'),
        ),
    ]
