# Generated by Django 5.1.6 on 2026-02-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0012_userreportpermission_is_direct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfolder',
            name='view_type',
            field=models.CharField(choices=[('business', 'Business Folders'), ('department', 'Department/Role'), ('anomalie', 'Anomalie')], help_text='Which custom view this folder belongs to', max_length=20),
        ),
    ]
