# Generated by Django 5.1.6 on 2026-03-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0013_alter_customfolder_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportref',
            name='server_url',
            field=models.URLField(blank=True, help_text='Base URL of the PBIRS server this report belongs to', max_length=512, null=True),
        ),
    ]
