# Generated by Django 5.1.6 on 2026-04-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0014_add_server_url_to_reportref'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportref',
            name='description',
            field=models.TextField(blank=True, help_text='Report description from PBIRS', null=True),
        ),
    ]
