# Generated by Django 5.1.6 on 2026-04-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0015_reportref_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportref',
            name='direction',
            field=models.CharField(blank=True, help_text='Direction concernée par le rapport', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reportref',
            name='pole',
            field=models.CharField(blank=True, help_text='Pôle organisationnel du rapport', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reportref',
            name='report_type',
            field=models.CharField(blank=True, choices=[('anomalie', 'Anomalie'), ('bibliotheque', 'Bibliothèque'), ('dashboard', 'Dashboard')], help_text='Type de rapport : Anomalie, Bibliothèque ou Dashboard', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reportref',
            name='societe',
            field=models.CharField(blank=True, help_text='Société à laquelle le rapport se rapporte', max_length=128, null=True),
        ),
    ]
