# Generated by Django 5.1.6 on 2026-04-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0017_reportref_is_consolide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportref',
            name='societe',
        ),
        migrations.AlterField(
            model_name='customfolder',
            name='view_type',
            field=models.CharField(choices=[('direction', 'Direction Folders'), ('department', 'Department/Role'), ('biblio', 'Bibliothèque'), ('anomalie', 'Anomalie'), ('consolide', 'Consolidé')], help_text='Which custom view this folder belongs to', max_length=20),
        ),
    ]
