# Generated by Django 5.1.6 on 2026-04-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0018_remove_reportref_societe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfolder',
            name='view_type',
            field=models.CharField(choices=[('direction', 'Direction Folders'), ('pole', 'Pôle Folders'), ('biblio', 'Bibliothèque'), ('anomalie', 'Anomalie'), ('consolide', 'Consolidé')], help_text='Which custom view this folder belongs to', max_length=20),
        ),
    ]
