# Generated by Django 5.1.6 on 2026-04-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0019_alter_customfolder_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportref',
            name='societe',
            field=models.CharField(blank=True, help_text='Société concernée par le rapport', max_length=128, null=True),
        ),
    ]
