# Generated by Django 5.1.6 on 2026-04-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0020_reportref_societe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBIRSServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A display name for this PBIRS instance', max_length=255, unique=True)),
                ('base_url', models.URLField(help_text='Base URL for the PBIRS API (e.g., http://server/Reports/api/v2.0)', max_length=512)),
                ('admin_username', models.CharField(help_text='Admin username (e.g., DOMAIN\\User)', max_length=255)),
                ('admin_password', models.CharField(help_text='Admin password', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this server is currently active')),
            ],
            options={
                'verbose_name': 'PBIRS Server',
                'verbose_name_plural': 'PBIRS Servers',
                'ordering': ['name'],
            },
        ),
    ]
