# Generated by Django 5.1.6 on 2026-05-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0021_pbirsserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfolder',
            name='view_type',
            field=models.CharField(choices=[('direction', 'Direction Folders'), ('pole', 'PÃ´le Folders'), ('biblio', 'BibliothÃ¨que'), ('anomalie', 'Anomalie'), ('consolide', 'ConsolidÃ©')], help_text='Which custom view this folder belongs to', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportref',
            name='direction',
            field=models.CharField(blank=True, help_text='Direction concernÃ©e par le rapport', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='reportref',
            name='is_consolide',
            field=models.BooleanField(default=False, help_text='Rapport consolidÃ© (multi-sociÃ©tÃ©s/pÃ´les â€” champs pÃ´le/sociÃ©tÃ©/direction non applicables)'),
        ),
        migrations.AlterField(
            model_name='reportref',
            name='pole',
            field=models.CharField(blank=True, help_text='PÃ´le organisationnel du rapport', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='reportref',
            name='report_type',
            field=models.CharField(blank=True, choices=[('anomalie', 'Anomalie'), ('bibliotheque', 'BibliothÃ¨que'), ('dashboard', 'Dashboard')], help_text='Type de rapport : Anomalie, BibliothÃ¨que ou Dashboard', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reportref',
            name='societe',
            field=models.CharField(blank=True, help_text='SociÃ©tÃ© concernÃ©e par le rapport', max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='MetadataOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('pole', 'Pôle'), ('direction', 'Direction'), ('societe', 'Société')], max_length=20)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Metadata Option',
                'verbose_name_plural': 'Metadata Options',
                'ordering': ['option_type', 'name'],
                'unique_together': {('option_type', 'name')},
            },
        ),
    ]
