# Generated by Django 5.1.6 on 2026-05-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0022_alter_customfolder_view_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataoption',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent option (e.g. link Société to a Pôle)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='powerbi_report.metadataoption'),
        ),
    ]
