# Generated by Django 5.1.6 on 2026-08-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0024_reportref_m2m_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfolder',
            name='view_type',
            field=models.CharField(choices=[('direction', 'Direction Folders'), ('pole', 'PÃ´le Folders'), ('biblio', 'BibliothÃ¨que'), ('anomalie', 'Anomalie'), ('consolide', 'ConsolidÃ©'), ('module', 'Module')], help_text='Which custom view this folder belongs to', max_length=20),
        ),
    ]
