# Generated by Django 5.1.6 on 2026-09-30 08:34

import django.db.models.deletion
import powerbi_report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0025_alter_customfolder_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataoption',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=powerbi_report.models.metadata_logo_path),
        ),
        migrations.AddField(
            model_name='reportref',
            name='mobile_report',
            field=models.ForeignKey(blank=True, help_text="Version téléphone (rapport au format portrait) affichée par l'application mobile", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktop_versions', to='powerbi_report.reportref'),
        ),
    ]
