# Generated by Django 5.1.6 on 2026-10-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0026_mobile_logo_and_phone_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportref',
            name='mobile_report',
        ),
    ]
