# Generated by Django 5.1.6 on 2026-10-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_report', '0027_remove_phone_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfolder',
            name='view_type',
            field=models.CharField(choices=[('direction', 'Direction Folders'), ('pole', 'Pôle Folders'), ('biblio', 'Bibliothèque'), ('anomalie', 'Anomalie'), ('consolide', 'Consolidé'), ('module', 'Module')], help_text='Which custom view this folder belongs to', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportref',
            name='direction',
            field=models.TextField(blank=True, help_text='Direction concernée par le rapport', null=True),
        ),
        migrations.AlterField(
            model_name='reportref',
            name='is_consolide',
            field=models.BooleanField(default=False, help_text='Rapport consolidé (multi-sociétés/pôles — champs pôle/société/direction non applicables)'),
        ),
        migrations.AlterField(
            model_name='reportref',
            name='pole',
            field=models.TextField(blank=True, help_text='Pôle organisationnel du rapport', null=True),
        ),
        migrations.AlterField(
            model_name='reportref',
            name='report_type',
            field=models.CharField(blank=True, choices=[('anomalie', 'Anomalie'), ('bibliotheque', 'Bibliothèque'), ('dashboard', 'Dashboard')], help_text='Type de rapport : Anomalie, Bibliothèque ou Dashboard', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reportref',
            name='societe',
            field=models.TextField(blank=True, help_text='Société concernée par le rapport', null=True),
        ),
    ]
